; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_src_filter = +<uno/> -<esp32/>
upload_port = COM12
monitor_port = COM12
monitor_speed = 9600
lib_deps = eoh-ltd/ERa@^1.6.4

[env:esp32]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps = 
	mobizt/Firebase Arduino Client Library for ESP8266 and ESP32 @ ^4.4.17
	eoh-ltd/ERa@^1.6.4
	4-20ma/ModbusMaster @ ^2.0.1
build_src_filter = +<esp32/> -<uno/>
upload_port = COM10
monitor_port = COM10
monitor_speed = 115200
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
build_flags = 
	-DBOARD_HAS_PSRAM=0
	-mfix-esp32-psram-cache-issue
	
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
